### ISSUE TITLE
СУБД ДЗ 1

### ISSUE THREAD

**Issue by rmnfl** [go-park-mail-ru/2024_1_commandName#26]
По https://github.com/go-park-mail-ru/2024_1_commandName/blob/commandName19_Migrations/db/normalized/relations.md
1. ER диаграмму нужно переделать: типы нужно либо совсем убрать, либо указать валидные, сейчас везде просто "type". Все связи между таблицами указаны как один к одному, а это, очевидно, не так. Можете посмотреть [вот тут, например](https://practicum.yandex.ru/blog/chto-takoe-er-diagramma/)

По https://github.com/go-park-mail-ru/2024_1_commandName/blob/commandName19_Migrations/db/migrations/20240413090410_new_user_table.sql
1.  [Timestamp](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_timestamp_.28without_time_zone.29)
2. created_date и lastseen_datetime - есть общепринятый суффикс _at, поэтому я бы поменял на created_at. Касается всех таблиц.
3. varchar(1) - [во-первых](https://wiki.postgresql.org/wiki/Don't_Do_This#Don.27t_use_varchar.28n.29_by_default). Оставьте текст и добавьте констреинт на длину в единицу. При чисто теоретическом увеличении числа типов до 9+, вам придется поменять только сам констреинт, не меняя тип данных колонки, что позволит не лочить базу надолго. Если же будете менять тип данных на varchar(2), это надолго залочит базу, поскольку изменение типа данных - довольно трудоемкая задача. При этом храниться на уровне Сишной реализации это будет абсолютно одинаково, поэтому разницы в быстродействии не будет.
4. avatar и avatar_path в двух разных таблицах. Давайте использовать одинаковый нейминг одинаковых вещей.
5. session. В чем разница между id и session_id? Зачем два поля? 
6. state в chat.contacts - не хотите создать таблицу-справочник и ссылаться на неё? Просто цифры - такое себе. Тоже самое про chat.chat и type в нем.
7. Констреинты на NOT NULL в многих полях в person. Точно нужны? У нас не может быть пользователя с незаполненными данными?
8. Не стоит ли добавить к chat created_at?

**Comment by ns-roxer** [comment]
На ER диаграмме первая колонка всегда содержит слово "type", должна наверное что-то другое

**Comment by ns-roxer** [comment]
Все timestamp заменить на timestamptz - https://github.com/go-park-mail-ru/2024_1_commandName/blob/commandName19_Migrations/db/migrations/20240413090410_new_user_table.sql

и будет зачет

**Comment by IvanNaum** [comment]
> На ER диаграмме первая колонка всегда содержит слово "type", должна наверное что-то другое

Fixed

**Comment by IvanNaum** [comment]
> 1. ER диаграмму нужно переделать: типы нужно либо совсем убрать, либо указать валидные, сейчас везде просто "type". Все связи между таблицами указаны как один к одному, а это, очевидно, не так. Можете посмотреть [вот тут, например](https://practicum.yandex.ru/blog/chto-takoe-er-diagramma/)

Fixed

**Comment by FunnyRockfish** [comment]
> 1. session. В чем разница между id и session_id? Зачем два поля?

id - это уникальное числовое значение чисто для БД, а вот sessionid - это сгенирированное значение символов, общией длины 32. Если необходимо - можем убрать id

**Comment by FunnyRockfish** [comment]
6 - fixed

**Comment by artmzhuk** [comment]
Пофиксил 2, 4, 8 (переименовал поля)

**Comment by rmnfl** [comment]
1. NOT NULL c username зря убрали все же
2. Тип данных TEXT у id в chat_type - сомнительно, но окэй
3. > > 1. session. В чем разница между id и session_id? Зачем два поля?
> 
> id - это уникальное числовое значение чисто для БД, а вот sessionid - это сгенирированное значение символов, общией длины 32. Если необходимо - можем убрать id

Да, давайте уберем, особого смысла в двух уникальных ключах я не вижу

**Comment by ns-roxer** [comment]
@rmnfl закрой, пожалуйста, issue.
